version: '3.8'

services:
  db:
    container_name: db-sigeli
    restart: always
    image: mariadb:10.5.8
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sigeli
    networks:
      - net

  phpmyadmin:
    container_name: sigeli-phpmyadmin
    restart: always
    image: phpmyadmin
    ports:
      - 8080:80
    networks:
      - net

  mailhog:
    container_name: sigeli-mailhog
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - net

networks:
  net:
    name: net