version: '3.8'

services:
  db:
    container_name: db-sigeli
    restart: always
    image: mariadb:10.5.8
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sigeli